# Fichier de configuration pour Netlify

# Section principale pour le 'build' de votre site
[build]
  # Le dossier à publier pour le site statique (la racine dans votre cas)
  publish = "."

# Section pour définir l'environnement de build
[build.environment]
  # Spécifie explicitement la version de Python à utiliser pour éviter 
  # toute incompatibilité.
  PYTHON_VERSION = "3.11"
