# =================================================================
# Fichier : netlify.toml
# =================================================================

# ---------------------------------------------------------------
# 1. Build et environnement
# ---------------------------------------------------------------
[build]
  command   = "npm install"          # Installation des dépendances
  functions = "netlify/functions"    # Dossier des fonctions serverless
  publish   = "."                    # Racine du site statique

[build.environment]
  PYTHON_VERSION = "3.11"            # Version de Python requise par vos fonctions

# ---------------------------------------------------------------
# 2. Fonctions serverless
# ---------------------------------------------------------------
[functions]
  included_files = [
    "netlify/functions/flora_gallica_pdfs/**"  # Inclusion des PDF nécessaires
  ]

# ---------------------------------------------------------------
# 3. Redirections (proxies WMS / API)
# ---------------------------------------------------------------
[[redirects]]
  from   = "/api/wms/inpn"           # Proxy vers l’INPN (WMS)
  to     = "/.netlify/functions/inpn-proxy"
  status = 200
  force  = true

[[redirects]]
  from   = "/api/gbif"               # Proxy vers le GBIF
  to     = "/.netlify/functions/gbif-proxy"
  status = 200
  force  = true

# ---------------------------------------------------------------
# 4. Plugins Netlify (un seul conservé)
# ---------------------------------------------------------------
[[plugins]]
  package = "@netlify/plugin-lighthouse"  # Audit de performance/SEO
